"""sync schedule and blocks

Revision ID: 1c721eb4be15
Revises: e6d95f0d6dcb
Create Date: 2026-02-02 22:33:42.929342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c721eb4be15'
down_revision: Union[str, Sequence[str], None] = 'e6d95f0d6dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barberblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_email', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barberblock_barber_email'), 'barberblock', ['barber_email'], unique=False)
    op.create_index(op.f('ix_barberblock_date'), 'barberblock', ['date'], unique=False)
    with op.batch_alter_table('appointment') as batch_op:
        batch_op.create_unique_constraint('uq_barber_start', ['barber_email', 'starts_at'])

    with op.batch_alter_table('barberschedule') as batch_op:
        batch_op.add_column(sa.Column('working_days', sa.JSON(), nullable=True))
        batch_op.drop_column('client_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barberschedule') as batch_op:
        batch_op.add_column(sa.Column('client_email', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('working_days')

    with op.batch_alter_table('appointment') as batch_op:
        batch_op.drop_constraint('uq_barber_start', type_='unique')
    op.drop_index(op.f('ix_barberblock_date'), table_name='barberblock')
    op.drop_index(op.f('ix_barberblock_barber_email'), table_name='barberblock')
    op.drop_table('barberblock')
    # ### end Alembic commands ###
